### ISSUE TITLE
Remote SQL access as a scheduled task

### ISSUE THREAD

**Issue by uSlackr** [jhoneill/GetSQL#2]
I've been using this module for months and it revolutionized my scripts (along with importexcel).  Thanks as always for the commitment to the community.

I have a simple script that connects to a remote SQL instance and dumps the results to a csv file.  it runs well interactively.  I need to move it to a scheduled task.  I've done many of these. but never one that access SQL.  When I run it, the connection fails.  The only evidence I have is this from the session transcript:
```Transcript started, output file is C:\Temp\sessionrecord.txt
WARNING: Error opening connection to 'Server=RT126AGLa.xxxx.com;Integrated Security=true;Initial Catalog=lansweeperdb;ApplicationIntent=ReadOnly'
PS>TerminatingError(): "System error."
```
- This is running using stored credentials and task runs so I know local sec settings are correct.
- I have run the script locally using the same credentials as the sch. task and it can access the db and pull the data fine.

Any sense for how I can get more error message out of this?

**Comment by jhoneill** [comment]
Glad it's proving useful.  

The easiest way to test this is with a two line script 
```
$conn =   New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList "<<YOUR CONNECTION STRING>>"
$conn.open 
```
If that fails but doesn't give enough info, you can add more to dump out parts of $error[0]  

There was a time when I knew this part of Windows properly,  but I'm relying on memory here ... so with a giant IIRC in front of it:
I think that the task scheduler can impersonate a user on the local system but needs credentials if the scheduled task connects to anything remote (i.e. `Integrated Security=true;`)   it needs the task options set like this 
![image](https://user-images.githubusercontent.com/16209593/176876866-7e71e4f4-e1b4-46ec-8b95-7e55fc92c934.png)

So that's the most obvious thing to check. It may be that you need to store the credentials securely and have the scheduled task use a connection string which contains `trusted_connection=false;uid=xxx;pwd=yyy`.  

Inside Get-SQL it looks at connection string it has been given and figures out if it needs to build something or if it can use it as-is . Then it does the new object / open that you see above, so if you can get that work that connection string should work with Get-SQL. It might need someone more expert in SQL server to say exactly how the scheduled task and connection string should be set up.

**Comment by uSlackr** [comment]
Thanks. I've tried both integrated and providing the creds directly and have the task configured as shown.  
So here's an interesting bit - I added the code you suggested and it does *not* error out.  Not what I expected.  So it's somehow related to the getsql usage.  

```
$Connect = "Server=RT126AGLa.somedom.com;Integrated Security=true;Initial Catalog=lansweeperdb;ApplicationIntent =ReadOnly"
    $hld = get-sql -MsSQLserver -connection $connect -Session TT
    TT $SQL | export-csv "$exportDir\LSEventlog.csv" #-notypeinformation 
    TT -close
```

**Comment by uSlackr** [comment]
I currently suspect this sever is in PW constrained language mode

**Comment by uSlackr** [comment]
I cannot use install-module xxx here.  I've copied the files over to the modules directory.   Should this work?

**Comment by jhoneill** [comment]
Yes, an xcopy install should be OK. Get-SQL relies on storing the connection object in a global hash table. 

that code is cut down from 

```
try                           { $Global:DbSessions[$Session].open() }
catch                         { Write-Warning -Message "Error opening connection to '$Connection'"  }
```

Possibly constrained language mode is doing something odd. But if you can create the object and open it, that's most of the job done

```
$Global:DbSessions = @{} 
$Global:DbSession['Test1'] =   New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList "<<YOUR CONNECTION STRING>>"
$Global:DbSession['Test1'].Open()
```
Would show if it is the global variable.

**Comment by uSlackr** [comment]
It comes down to authentication.  As a scheduled task, if I specify integrated security = true, SQL is saying I'm trying to login using an anonymous user. If I specify the username and password, SQl says I'm trying to use SQL auth.  I need to impersonate the user the task is running as.  Trying to work that out

**Comment by uSlackr** [comment]
> Yes, an xcopy install should be OK. Get-SQL relies on storing the connection object in a global hash table.
> 
> that code is cut down from
> 
> ```
> try                           { $Global:DbSessions[$Session].open() }
> catch                         { Write-Warning -Message "Error opening connection to '$Connection'"  }
> ```
> 
> Possibly constrained language mode is doing something odd. But if you can create the object and open it, that's most of the job done
> 
> ```
> $Global:DbSessions = @{} 
> $Global:DbSession['Test1'] =   New-Object -TypeName System.Data.SqlClient.SqlConnection -ArgumentList "<<YOUR CONNECTION STRING>>"
> $Global:DbSession['Test1'].Open()
> ```
> 
> Would show if it is the global variable.

I confirmed the Sch. task is NOT in constrained mode.  It's all about failed auth.  The credentials of the Sch. task user are not being passed along
